//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerInterruptions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interruption
    {
        public int eventID { get; set; }
        public string localGov { get; set; }
        public System.DateTime startDate { get; set; }
        public System.TimeSpan startTime { get; set; }
        public int customers { get; set; }
        public int duration { get; set; }
        public string reason { get; set; }
    }
}
